/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.lmu.cs.xlg.iki.syntax;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int LETTER = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"begin\"",
    "\"var\"",
    "\"read\"",
    "\"write\"",
    "\"while\"",
    "\"end\"",
    "\"loop\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\":=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<INTLIT>",
    "<ID>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
  };

}
