/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMTYPE = 27;
  /** RegularExpression Id. */
  int STRTYPE = 28;
  /** RegularExpression Id. */
  int BOOLTYPE = 29;
  /** RegularExpression Id. */
  int FUNTYPE = 30;
  /** RegularExpression Id. */
  int REGEXTYPE = 31;
  /** RegularExpression Id. */
  int NULLTYPE = 32;
  /** RegularExpression Id. */
  int INTLIT = 33;
  /** RegularExpression Id. */
  int STRING = 34;
  /** RegularExpression Id. */
  int CHARLIT = 35;
  /** RegularExpression Id. */
  int BR = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"-\"",
    "\"+\"",
    "\"/\"",
    "\"*\"",
    "\"**\"",
    "\":=\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\",\"",
    "\"..\"",
    "\"...\"",
    "\"f:\"",
    "\"8:\"",
    "\"->\"",
    "\"#\"",
    "\"$\"",
    "\"^\"",
    "\"f\"",
    "\"@\"",
    "\"~\"",
    "<INTLIT>",
    "<STRING>",
    "<CHARLIT>",
    "\";\"",
    "\"!\"",
    "\"\"",
    "\":=:\"",
    "\"p:\"",
    "\"??:\"",
    "\"?\"",
    "\":\"",
    "\"??\"",
    "\"T\"",
    "\"F\"",
    "\"<\"",
    "\">\"",
    "\"%\"",
    "\"_\"",
    "\"#:{\"",
    "\"=>\"",
  };

}
